"""empty message

Revision ID: 2ddada3a63e7
Revises: 522ab8856717
Create Date: 2021-06-13 11:59:42.297560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddada3a63e7'
down_revision = '522ab8856717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('food_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'food', ['food_id'], ['id'])
    op.create_foreign_key(None, 'order', 'worker', ['worker_id'], ['id'])
    op.drop_column('order', 'worker')
    op.drop_column('order', 'food')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('food', sa.INTEGER(), nullable=True))
    op.add_column('order', sa.Column('worker', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'food', ['food'], ['id'])
    op.create_foreign_key(None, 'order', 'worker', ['worker'], ['id'])
    op.drop_column('order', 'food_id')
    op.drop_column('order', 'worker_id')
    # ### end Alembic commands ###
