"""empty message

Revision ID: be5b07bd562c
Revises: c3b252aaee7c
Create Date: 2021-05-18 17:10:08.637215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5b07bd562c'
down_revision = 'c3b252aaee7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('worker', sa.Integer(), nullable=True),
    sa.Column('food', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food'], ['food.id'], ),
    sa.ForeignKeyConstraint(['worker'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
